version: '2'

networks:
    fabric-network:
services:
  ca.org1.example.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true            
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    #command: tail -f /dev/null
    volumes:
      - ./fabric-ca/org1.example.com/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.org1.example.com
    networks:
      - fabric-network
  
  ca.org2.example.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true            
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - 8054:8054
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    #command: tail -f /dev/null
    volumes:
      - ./fabric-ca/org2.example.com/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.org2.example.com
    networks:
      - fabric-network

  ca.orderer.example.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.orderer.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true            
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - 9054:9054
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    #command: tail -f /dev/null
    volumes:
      - ./fabric-ca/orderer.example.com/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.orderer.example.com
    networks:
      - fabric-network